Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], 
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [5]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [16]:
N = a.shape[0]
a_centered_sp = a_centered[:,0].dot(a_centered[:,1])
a_centered_sp/(N-1)

2.0

Задание 4** В этом задании проверьте получив`шееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1

In [20]:
a_centerd_sp_2 = np.cov(a.T)[0, 1]
a_centerd_sp_2

2.0

Задание 5**
Создайте одномерный массив z случайных нормально распределенных целых чисел от -50 до 50 включительно размерности 8. Найдите индексы положительных объектов.

In [23]:
r = np.random.randn(-50, 50, 8)
r

ValueError: negative dimensions are not allowed

Задание 6**
Создайте двумерный массив X случайных равномерно распределенных целых чисел от 0 до 255 включительно размерности 10 на 5. (Здесь снова считаем, что каждый столбец - это признак, а строка - наблюдение.)
Найдите среднее значение и стандартное отклонение по каждому признаку.
Вычислите массив X_standard, отняв от каждого признака среднее и поделив на стандартное отклонение.
Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице.

Задание 7**
Создайте два одномерных массива размерности 512 с любыми значениями. Будем считать, что каждый массив - это наблюдение с 512 признаками. 
Найдите разницу между двумя массивами. Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный. Посчитайте L2 норму для этих двух массивов с помощью numpy.linalg.

Задание 8**
Используйте ранее созданный массив X.
Найдите минимальное значение и максимальное по каждому признаку.
Вычислите массив X_norm, отняв от каждого признака минимальное и поделив на разницу максимального и минимального.
Убедитесь, что теперь минимальное значение стало равно 0, а максимальное - 1.