In [13]:
import numpy as np

#### 1.Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [14]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2.Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [15]:
a1 = np.reshape(a, (2, 6))
a2 = np.reshape(a, (6,2))
a3 = np.reshape(a, (3,4))
a4 = np.reshape(a, (4,3))
a5 = np.reshape(a, (12,1))
display(a1)
display(a2)
display(a3)
display(a4)
display(a5)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### 3.Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [16]:
b1 = np.reshape(a, (2, -1))
b2 = np.reshape(a, (6,-1))
b3 = np.reshape(a, (3,-1))
b4 = np.reshape(a, (-1,1))
b5 = np.reshape(a, (-1,1))
display(a1)
display(a2)
display(a3)
display(a4)
display(a5)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### 4.Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: Нет, так как для каждой строки используется отдельный список. При этом все списки влючены в 'общий список'

#### 5.Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [17]:
c0 = np.random.randn(3,4)
display(c0)
display(c0.size)
c1 = c0.reshape(1, 12)[0]
display(c1)
display(c1.size)

array([[ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819]])

12

array([ 0.24196227, -1.91328024, -1.72491783, -0.56228753, -1.01283112,
        0.31424733, -0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ,
        0.0675282 , -1.42474819])

12

#### 6.Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [18]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7.Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [19]:
#в первом случае массив одномерный, во втором двумерный
b = np.arange(20,1,-2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

#### 8.Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [20]:
a = np.zeros((2, 2))
b = np.ones((3,2))
a_b = np.hstack((b, a))
display(a_b)
display(a_b.size)

array([[0., 0., 1., 1., 1.],
       [0., 0., 1., 1., 1.]])

10

#### 9.Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [21]:
a = np.arange(0,12)
A = a.reshape(4,3)
display(A)
At = A.T
display(At)
B = A.dot(At)
display(B, f'Рамер:{B.shape}')
display(f'Определитель B: {np.linalg.det(B)}')

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

'Рамер:(4, 4)'

'Определитель B: 0.0'

Ответ: так как определитель B равен 0, то у матрицы B нет обратной

#### 10.Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [25]:
np.random.seed(42)

#### 11.Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [26]:
c = np.random.randint(0,16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

#### 12.Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [45]:
C = c.reshape((4,-1))
display(C)
D = 10*B + C
display(D)
D_det = np.linalg.det(D)
print(f'Определитель = {D_det}')
D_rank = np.linalg.matrix_rank(D)
print(f'Ранг D = {D_rank}')
D_inv = np.linalg.inv(D)
print(f'Обратная матрица:\n{D_inv}')

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

array([[  56,  143,  242,  334],
       [ 150,  507,  872, 1224],
       [ 236,  869, 1492, 2126],
       [ 330, 1230, 2127, 3024]])

Определитель = -1741607.9999999756
Ранг D = 4
Обратная матрица:
[[ 0.135368   -0.09412681 -0.0250975   0.04079219]
 [-0.17297808  0.16351785  0.1740805  -0.16946638]
 [-0.05802224  0.09496052 -0.10651536  0.04285695]
 [ 0.09639712 -0.12303113  0.00685229  0.03466452]]
[[ 1.00000000e+00 -7.10542736e-15 -8.88178420e-16  1.77635684e-15]
 [-1.42108547e-14  1.00000000e+00  0.00000000e+00 -7.10542736e-15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00 -1.42108547e-14]
 [ 0.00000000e+00  0.00000000e+00 -3.55271368e-15  1.00000000e+00]]


#### 13.Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [69]:
D_inv[D_inv< 0] = 0
D_inv[D_inv>0] = 1
print(f'Проверка:{D_inv[~(D_inv==0) & ~(D_inv==1)]}\n')
print(f'Модифиципованная D_inv: \n{D_inv}\n')
print(f'B:\n{B}\n')
print(f'C:\n{C}\n')
E = np.where(D_inv == 1, B , 0) + np.where(D_inv == 0, C, 0) 

print(f'Матрица Е:\n{E}')

Проверка:[]

Модифиципованная D_inv: 
[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 1.]]

B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

C:
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]

Матрица Е:
[[  5   3  12  32]
 [ 10  50  86   4]
 [  6  86   2 212]
 [ 32  10 212 302]]
